//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.18 at 10:14:10 PM GMT 
//


package ws.biotea.ld2rdf.util.ncbo.annotator.jaxb.newgenerated;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}annotatedClass"/>
 *         &lt;element ref="{}hierarchyCollection"/>
 *         &lt;element ref="{}annotationsCollection"/>
 *         &lt;element ref="{}mappingsCollection"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "annotatedClass",
    "hierarchyCollection",
    "annotationsCollection",
    "mappingsCollection"
})
@XmlRootElement(name = "annotation")
public class Annotation {

    @XmlElement(required = true)
    protected AnnotatedClass annotatedClass;
    @XmlElement(required = true)
    protected HierarchyCollection hierarchyCollection;
    @XmlElement(required = true)
    protected AnnotationsCollection annotationsCollection;
    @XmlElement(required = true)
    protected MappingsCollection mappingsCollection;

    /**
     * Gets the value of the annotatedClass property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotatedClass }
     *     
     */
    public AnnotatedClass getAnnotatedClass() {
        return annotatedClass;
    }

    /**
     * Sets the value of the annotatedClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotatedClass }
     *     
     */
    public void setAnnotatedClass(AnnotatedClass value) {
        this.annotatedClass = value;
    }

    /**
     * Gets the value of the hierarchyCollection property.
     * 
     * @return
     *     possible object is
     *     {@link HierarchyCollection }
     *     
     */
    public HierarchyCollection getHierarchyCollection() {
        return hierarchyCollection;
    }

    /**
     * Sets the value of the hierarchyCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link HierarchyCollection }
     *     
     */
    public void setHierarchyCollection(HierarchyCollection value) {
        this.hierarchyCollection = value;
    }

    /**
     * Gets the value of the annotationsCollection property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationsCollection }
     *     
     */
    public AnnotationsCollection getAnnotationsCollection() {
        return annotationsCollection;
    }

    /**
     * Sets the value of the annotationsCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationsCollection }
     *     
     */
    public void setAnnotationsCollection(AnnotationsCollection value) {
        this.annotationsCollection = value;
    }

    /**
     * Gets the value of the mappingsCollection property.
     * 
     * @return
     *     possible object is
     *     {@link MappingsCollection }
     *     
     */
    public MappingsCollection getMappingsCollection() {
        return mappingsCollection;
    }

    /**
     * Sets the value of the mappingsCollection property.
     * 
     * @param value
     *     allowed object is
     *     {@link MappingsCollection }
     *     
     */
    public void setMappingsCollection(MappingsCollection value) {
        this.mappingsCollection = value;
    }

}
